### ISSUE TITLE
Getting Exception on reading version.yml

### ISSUE THREAD

**Issue by emiliopedrollo** [antonioribeiro/version#14]
I'm getting the following exception when I try to use any command:

    [Symfony\Component\Debug\Exception\FatalThrowableError]            
    Call to undefined method Symfony\Component\Yaml\Yaml::parseFile()

**Comment by antonioribeiro** [comment]
Looks like you have a different version of Symfony\Yaml installed, strangely, could you please give me the result of your: 

```
composer show
```

No need to send everything, laravel, illuminate, symfony and pragmarx is enough.

**Comment by antonioribeiro** [comment]
Changed some of the dependencies versions, could you, please, try again?

**Comment by emiliopedrollo** [comment]
Hello Antonio,

I'm currently using this package at a work project and will only be able to
actually test it monday. But then I'll let you know if it worked.

*Emílio B. Pedrollo*
Full Stack Developer

+55 (55) 99134-7922

**Comment by stefanzweifel** [comment]
Hey,

I've the same issue in a Laravel 5.5 project. `composer show | grep "symfony/yaml"` gives me:

```shell
symfony/yaml                       v3.3.13 Symfony Yaml Component
```

**Comment by antonioribeiro** [comment]
Yeah, just found there was no parseFile on Symfony 3.3, my bad.

**Comment by stefanzweifel** [comment]
Just ran `composer update` and the `symfony/yaml` package has been updated to `v3.4.0` and resolved the problem:

```
symfony/yaml                       v3.4.0  Symfony Yaml Component
```

Maybe the `symfony/yaml` constraint on `pragmarx/yaml` could fix that?

**Comment by antonioribeiro** [comment]
Should be fixed now.

Decided to keep supporting Symfony 3.3, since lots of other one would probably have it installed in their projects. Thanks for reporting guys.
