### ISSUE TITLE
Thoughts on Changelog..?

### ISSUE THREAD

**Issue by blomdahldaniel** [antonioribeiro/version#29]
Hi!
Looks like a neat package! Though i feel like versioning also comes with changelogs? What are your thoughts on that and is it anything you plan on adding as well?

**Comment by antonioribeiro** [comment]
Yeah, I would really like to do something in this area, but I'm not really sure what would be a good way to store and keep track of the changelog: 

- One big file in a /config/version path?
- Separate files, one per version?
- Should we use a command to add changelogs or developers would have to maintain the file theirselves?
- What format should it use ([changelog](http://keepachangelog.com/en/1.0.0/) or yaml)?
- If yaml, should we then generate the changelog.md?
- If changelog, would we need to parse it at some point?

**Comment by blomdahldaniel** [comment]
Wow. I now (super slow response time..) realize that everything gets a bit more complex..

My spontaneous feeling is separate files for each version and structured in directories..? 

Also think that just a markdown file for each changelogs would be enough? Or is it not complex enough?

So folder structure like this:

- 1.X.X/
  - 1.0.X/
  - 1.1.X/
  - 1.2.X/
    - 1.2.0.md
    - 1.2.X/
      - 1.2.1.md
      - 1.2.2.md
- 2.X.X/
  - 2.1.X/
    - 2.1.0.md
    - 2.1.1/

**Command** to generate an empty MD file for each version would be nice.

Then display everything with a table of contents similar to the folder structure, linking to each release. 

Just some thoughts on top of my head..

Would be a total mess if you would want to rearrange some versions.. but I hope that is forbidden in general any way..?

Maybe also try to combine this with git versioning..? Or at least try to instruct in how to use is to also suggest versioning inside git..? Or is that bit to much and not in the interest of this repo..?

Just some thoughts from a rookie in this topic. You do whatever feels right and inspiring to you. Props to you for putting out a open source project and exposing your thoughts and ideas. 💪😎

**Comment by AlexGodbehere** [comment]
This would be the holy grail for me. I'm looking for an elegant way to alert users when a new version is published, linking to a changelog. If I get a chance I might make a fork and try to get something working.

**Comment by antonioribeiro** [comment]
A whole new version has come out. And I'm still not sure how to tackle something like this. If you still want to work on this one, please ask to reopen.
