### ISSUE TITLE
Conflict with Blade directives from other packages

### ISSUE THREAD

**Issue by softquantum** [antonioribeiro/version#31]
Hi Antonio,

Thank you for your hard work, much appreciated.

I am using your package in a project with https://github.com/spatie/laravel-permission.  Your version package declares the version directive in the register method and it seems to get the other directives to go away.  I do not know all the internals but moving it to the boot method solved my problem.  I can do a PR if this can be a suitable solution.

```PHP
/**
     * Boot Service Provider.
     */
    public function boot()
    {
        $this->publishConfiguration();
        $this->registerBlade();
    }
```

**Comment by antonioribeiro** [comment]
You can now configure the Blade directive: https://github.com/antonioribeiro/version/blob/master/src/config/version.yml#L2

**Comment by antonioribeiro** [comment]
Yeah, package was booting Blade too soon, moved to boot() method.

Thank you!
