### ISSUE TITLE
git-remote doesn't work for private repos

### ISSUE THREAD

**Issue by ahinkle** [antonioribeiro/version#34]
version_source: git-remote
.env -> VERSION_GIT_REMOTE_REPOSITORY=(private repo link)

Not working for private repos. Any thoughts here?

Thanks.

**Comment by ahinkle** [comment]
Resorted to just using git-local instead. Not a major issue. Thanks for your project!

**Comment by seandelaney** [comment]
I'm using private repos on Gitlab and I get prompted for my username and password, so it does work.

**Comment by seandelaney** [comment]
The Gitlab has a lot of token access options for private repos. Github is the same.

`git clone https://gitlab-ci-token:${Personal Access Tokens}@gitlab.com/username/repo.git`

`git clone https://oauth2:${Personal Access Tokens}@gitlab.com/username/repo.git`

or using username and password:

`git clone https://${username}:${password}@gitlab.com/username/repo.git`

or by input your password:

`git clone https://${username}@gitlab.com/username/repo.git`

So in your `version.yml` file, set the `repository` value like so:

`repository: 'https://oauth2:${Personal Access Tokens}@gitlab.com/username/repo.git'`

Hope this makes sense.

**Comment by ahinkle** [comment]
Thanks man!
