### ISSUE TITLE
How to have different Caching Key for different ENV

### ISSUE THREAD

**Issue by perdeepOsingh** [antonioribeiro/version#40]
Great package, works very well. I was wondering is there a way just like we do in any config/*.php that by looking at env we can change values?

I am mainly looking at cache key, can I use different caching key for different env?

I can see it as a good use case, few of our environments are sharing cache so it always mess up the build number, which is set to be git hash.

Once again thanks for very nice product.

**Comment by Medalink** [comment]
I have a build script that does not have access to the same .env as where I run the main app so I solved it by using a temporary environment variable when calling the artisan command:

```bash
env CACHE_DRIVER="array" php artisan version:refresh
```

Maybe something like that can work for you?

**Comment by antonioribeiro** [comment]
Version 1.0.0 only uses the .yml file o store the version. No more caching.
