### ISSUE TITLE
Instantiating xml file from IoC Container

### ISSUE THREAD

**Issue by petermein** [antonioribeiro/version#45]
When trying to instantiate the Version model, I get this error. 
`Class pragmarx.yaml does not exist `

Seems the Model is tryting to get an XML file from the IoC that is not registered. 

When digging deeper
`$yaml = $this->instantiateClass($yaml ?: app('pragmarx.yaml'), 'yaml');`
This line is the culprit, and $yaml parameter seems off here. 

`$yaml = $this->instantiateClass($config ?: app('pragmarx.yaml'), 'yaml');`
This seems a better option as its get the propery out of the config

**Comment by antonioribeiro** [comment]
How are you trying to instantiate it?

**Comment by antonioribeiro** [comment]
You said 

> Version  model

But I'm assuming it's "Version class", right?

**Comment by antonioribeiro** [comment]
If you don't want to use the Facade

``` php
dd(Version::format());
```

The best ways to instantiate it are 

``` php
$version = new \PragmaRX\Version\Package\Version();

dd($version->format());
```

Or

``` php
dd(app(\PragmaRX\Version\Package\Version::class)->format());
```

All of them are working fine here. As long as you publish the config file:

``` bash
php artisan vendor:publish --provider="PragmaRX\Version\Package\ServiceProvider"
```

**Comment by petermein** [comment]
I'm not instantiating it myself, its the service provider doing it when running any of the possibilities to use the library. Like the blade directive or the console command. 

`    protected function registerService()
    {
        $this->app->singleton('pragmarx.version', function () {
            $version = new Version($this->config);
            $version->setConfigFileStub($this->getConfigFileStub());

            return $version;
        });
    }`

But i've worked around it and inject the config file directly instead of getting it from the Container
