### ISSUE TITLE
Version inside of another config file.

### ISSUE THREAD

**Issue by Medalink** [antonioribeiro/version#46]
I am needing a way to get the version inside of another config file. My thoughts on a new command that would be something like laravel's key:generate that would update the .env with the current version. Thoughts?

**Comment by trevorgehman** [comment]
I'd also like to be able to do this... I'm using Bugsnag and I have to set the `app_version` in the `config/bugsnag.php` file. Trying to figure out how to use this package and accomplish that.

**Comment by maciej-laskowski** [comment]
@trevorgehman I have the exact same use case. I added `Bugsnag::setAppVersion` to my `app/Exceptions/Handler.php` report method and it works. Here are the important bits:

```
<?php

namespace App\Exceptions;

use PragmaRX\Version\Package\Version;
use Bugsnag\BugsnagLaravel\Facades\Bugsnag;

class Handler extends ExceptionHandler
{
    public function report(Exception $exception)
    {
        Bugsnag::setAppVersion((new Version())->format('version'));
        Bugsnag::notifyException($exception);
    }
}

```
Maybe you found another solution in the meantime?

**Comment by trevorgehman** [comment]
That looks like a good workaround @maciej-laskowski.

**Comment by philbenoit** [comment]
I'm trying to get the version into Swagger documentation. 

The l5-swagger package requires constants to be set in a config file. I am having trouble getting the version out of this package into the swagger config file. Would be nice to have a clean setup for maintaining version within our docs. 

Any ideas? I have tried all the examples in the docs and get the following

```
use PragmaRX\Version\Package\Version;
Class pragmarx.yaml does not exist

$version = new \PragmaRX\Version\Package\Version();
Class pragmarx.yaml does not exist

```

**Comment by antonioribeiro** [comment]
I think we have some solutions here, so closing it for now. 

@maciej-laskowski, you example is now in the docs, thank you!
