### ISSUE TITLE
@version directive doesn't always work straight away

### ISSUE THREAD

**Issue by estin92** [antonioribeiro/version#47]
Laravel: 5.6.*
PHP: 7.1.*

The directive worked perfectly on our development environment straight away, but when transferred to the client's staging server we just saw the custom @version('compact') blade directive.

Removed the vendor directory and reinstalled all packages but still no joy. Both servers could read/write to the configuration file, but it didn't render the content from the custom blade directive.

Despite no caching being configured on our development environment, the live environment required the views cache to be cleared using `php artisan view:clear`

It may be worth adding to the docs for reference.

**Comment by antonioribeiro** [comment]
If this is still a problem un version 1.0, please ask to reopen.
