### ISSUE TITLE
Getting "Class pragmarx.yaml does not exist" 

### ISSUE THREAD

**Issue by gmartinez** [antonioribeiro/version#57]
Hi,

 The package is working ok, but now I am trying to get the version number from a file that is under config/ directory (trying to set the release value on sentry.io configuration).

 Is there a way to use the library from other than a file under app directory ?

(I think I am using 0.2.7)

**Comment by strausmann** [comment]
i have the same problem, how can i use the version with sentry?
Sentry has your own config file.

**Comment by antonioribeiro** [comment]
How do I reproduce this?

**Comment by antonioribeiro** [comment]
Please ask to reopen if you still interested and are able to give me some clue on reproducing.

**Comment by perezale** [comment]
It's not a bug, rather an architectural design misuse.  At [config/sentry.php](https://github.com/getsentry/sentry-laravel/blob/master/config/sentry.php), there is no app environment available so you can't just do```'version' => new \PragmaRX\Version\Package\Version()```.  (As recommended in [this comment](https://github.com/getsentry/sentry-laravel/blob/736e08f16737e65249dec34454fb8dbf8eb2abb3/config/sentry.php#L8) for git-based versioning).

The solution I found so far is setting these values at execution time as detailed before ([here](https://github.com/antonioribeiro/version/issues/57#issuecomment-525858696)).
