### ISSUE TITLE
Remote repository not pulling from .env file if Laravel config is cached 

### ISSUE THREAD

**Issue by arharp** [antonioribeiro/version#60]
Whenever the Laravel application config is cached (via `php artisan config:cache`) the VERSION_GIT_REMOTE_REPOSITORY setting in the `.env` is no longer available to the version.yml file. This is expected Laravel behavior as described here: https://laravel.com/docs/5.8/configuration#configuration-caching

Perhaps a better solution for handling the package config would be to have a standard `config/version.php` file and then only store the current version and build numbers in a version.yml file in the project root.

**Comment by arharp** [comment]
@antonioribeiro I was able to fix this by setting the repo in `config/app.php` and then using `{{ config('app.git_remote_repository') }}` in `version.yml`.

**Comment by antonioribeiro** [comment]
Yeah, this is surely a config bug. We will probably have to create a version.php file to store our .env related config stuff. But it's a nice fix, thanks for sharing it.

**Comment by antonioribeiro** [comment]
Just added a comment to the version.yml file so people don't use env() anymore
