### ISSUE TITLE
Support SemVer pre-release labels

### ISSUE THREAD

**Issue by thicolares** [antonioribeiro/version#61]
Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92.
(Source: https://semver.org/#spec-item-9)

**Currently**
- When I create an annotated tag with a pre-release label (accordingly to the SemVer specs) -- e.g. `v0.8.0-beta`, the label is ignored.
- When I update the matcher regex, the `Git.php` handle it as the build

```php
    public function version($type)
    {
        $version = $this->extractVersion($this->getVersionFromGit());

        return [
            'major' => $this->getMatchedVersionItem($version, 1),

            'minor' => $this->getMatchedVersionItem($version, 2),

            'patch' => $this->getMatchedVersionItem($version, 3),

            'build' => $this->getMatchedVersionItem($version, 4),
        ][$type];
    }
```

**Proposal**
- Support SemVer pre-release labels as the 4th default property. Thus the build would be the 5th.

(I intend myself to create a PR for that)

**Comment by antonioribeiro** [comment]
I like the idea very much and probably will accept your PR, but we have to think if this change may impact current users, as you are proposing making it the 4th element and not the 5th.

**Comment by thicolares** [comment]
You're right. I will consider that and other things to keep backward compatibility.

**Comment by thicolares** [comment]
Furthermore, if the packaged intends to follow semver's specs, then:

> Build metadata MAY be denoted by appending a plus sign and a series of dot separated identifiers immediately following the patch or pre-release version
> ...
> Examples: 1.0.0-alpha+001, 1.0.0+20130313144700, 1.0.0-beta+exp.sha.5114f85.

https://semver.org/#spec-item-10

**Comment by jpscharf** [comment]
Maybe you could use [nikolaposa/version](https://github.com/nikolaposa/version) to parse the version.

```php
use Version\Version;
use Version\Extension\PreRelease;

...

    public function version($type)
    {          
        $version = Version::fromString($this->getVersionFromGit());
    
        return [
            'major' => $version->getMajor() ?? 0,
            'minor' => $version->getMinor() ?? 0,
            'patch' => $version->getPatch() ?? 0,
            'pre_release' => $version->getPreRelease(),
            'build' => $version->getBuild().
        ][$type];
    }
```

**Comment by antonioribeiro** [comment]
Version 1.0.0 tagged to support this. Thank you!
