### ISSUE TITLE
version:refresh command issue in 1.0

### ISSUE THREAD

**Issue by shabushabu** [antonioribeiro/version#68]
I noticed that the `version:refresh` command has been removed in version 1.0. Is there an alternative we can use? Also, the documentation is out of sync as it still recommends to use `version:refresh` in a git hook.

**Comment by antonioribeiro** [comment]
Absorb is king now, there’s no cache anymore so no need to refresh. You can
just

‘’’
php artisan version:absorb
‘’’
-- 
Antonio Carlos Ribeiro
acr@antoniocarlosribeiro.com

Enviado do meu iPhone

**Comment by antonioribeiro** [comment]
Absorb is king now, there’s no cache anymore so no need to refresh. You can
just

``` bash
php artisan version:absorb
```

**Comment by shabushabu** [comment]
Alright, cheers!

**Comment by bolechen** [comment]
plz update the `README` file
