### ISSUE TITLE
Failing in Laravel 6.x

### ISSUE THREAD

**Issue by baradhili** [antonioribeiro/version#72]
Running Laravel 6.4.1 and Version 1.0.2 
getting ` ErrorException (E_ERROR)
Undefined index: optional (View: /home/vagrant/code/resources/views/layouts/main.blade.php) (View: /home/vagrant/code/resources/views/layouts/main.blade.php)
Previous exceptions
    Undefined index: optional (View: /home/vagrant/code/resources/views/layouts/main.blade.php) (0)
    Undefined index: optional (0)
`

Was working fine in 5.8

Thanks

**Comment by antonioribeiro** [comment]
By the error trace, this doesn't look like something in Version. Do you have antonioribeiro/version/* in any place in those logs?
