### ISSUE TITLE
PHP8

### ISSUE THREAD

**Issue by CraigMonva** [antonioribeiro/version#93]
Hi,

When could we expect PHP8.0 support? This is our last package needing support.

Thanks.

**Comment by dostrog** [comment]
Strange situation… for v 1.2.3

Here on GitHub I see in composer.json `"php": ">=7.0",` in vendor `"php": "^7.0",`

```
$ composer show pragmarx/version
name     : pragmarx/version
descrip. : Take control over your Laravel app version
keywords : laravel, version, versioning
versions : * v1.2.3
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
homepage :
source   : [git] https://github.com/antonioribeiro/version.git 691fd35c94eea9d58a9851f8fdb6c2dcee85af9a
dist     : [zip] https://api.github.com/repos/antonioribeiro/version/zipball/691fd35c94eea9d58a9851f8fdb6c2dcee85af9a 691fd35c94eea9d58a9851f8fdb6c2dcee85af9a
path     : /Users/dostrog/projects/taxbase/vendor/pragmarx/version
names    : pragmarx/version

support
issues : https://github.com/antonioribeiro/version/issues
source : https://github.com/antonioribeiro/version/tree/v1.2.3

autoload
psr-4
PragmaRX\Version\Package\ => src/package
PragmaRX\Version\Tests\ => tests/

requires
laravel/framework >=5.5.33
php ^7.0
pragmarx/yaml ^1.0
symfony/process ^3.3|^4.0|^5.0

requires (dev)
orchestra/testbench 3.4.*|3.5.*|3.6.*|3.7.*|4.*|5.*
phpunit/phpunit ~5|~6|~7|~8|~9
```

packagist has old version?

**Comment by dostrog** [comment]
solved it by use `"pragmarx/version": ">=v1.2.3"` in composer.json. Loaded
```
$ c show pragmarx/version
name     : pragmarx/version
descrip. : Take control over your Laravel app version
keywords : laravel, version, versioning
versions : * 9999999-dev, * dev-master
type     : library
…
```

Thanx!

**Comment by nabeelio** [comment]
`"pragmarx/version": ">=v1.2.3"` is not working for me. Can a new tagged version be published with this fix?

**Comment by nabeelio** [comment]
@antonioribeiro Hi, can you tag and publish a new version with the PHP 8 compat? This is a blocker for me with updating our apps for PHP 8 compatibility and I don't want to set the version to look at the master branch.

**Comment by KieronWiltshire** [comment]
I could also really do with this being updated!

**Comment by antonioribeiro** [comment]
Can anyone jump in and help make tests pass on Github Actions?
I believe there's still one test to be fixed.

**Comment by antonioribeiro** [comment]
Well... tests are passing fine on PHP 8, so version is tagged.
But I still need help with making them pass on Github actions.
