### ISSUE TITLE
Best way to approach my desired workflow

### ISSUE THREAD

**Issue by sburkett** [antonioribeiro/version#95]
FYI - we use github, but we don't use tags/releases.

What I want to do is to be able to manually alter the major and minor numbers via artisan commands (`mode: increment`?), but have the patch number increment automatically with each commit.

Any thoughts on how best to approach this sort of thing? Thanks in advance!

**Comment by antonioribeiro** [comment]
Those commands are supposed to be incrementers:

```
php artisan version:major
php artisan version:minor
php artisan version:patch
```

Aren't they working for you?

**Comment by sburkett** [comment]
Yes, those commands work great. :) But what I would like is for all commits to automatically increment the patch level.

I figured out a way to do it, though :)

For others who may be interested, I created a git hook in `.git/hooks/pre-commit` which simply looks like:

```
#!/bin/sh
php artisan version:commit
git add ./config/version.yml
```
Be sure to `chmod 755 ./git/hooks/pre-commit` so it will be executable.

Now, whenever we make a commit, it will automatically update the `commit` portion of the SemVer string. Of course, if you wanted to update the patch level instead (or some other portion) just change the artisan command in the hook script to do `php artisan version:patch`, or whatever.

**Comment by antonioribeiro** [comment]
Great, thanks for sharing!
